- id: pretty-format-golang
  name: Go Formatter
  description: Runs gofmt over golang source files.
  entry: pretty-format-golang
  language: python
  types: [go]
  files: ^.+\.go$
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-java
  name: Google Java Formatter
  description: Runs Google Java Formatter over Java source files
  entry: pretty-format-java
  language: python
  types: [java]
  files: ^.+\.java$
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-kotlin
  name: KTLint
  description: Runs KTLint over Kotlin source files
  entry: pretty-format-kotlin
  language: python
  types: [kotlin]
  files: ^.+\.kt$
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-toml
  name: Pretty format TOML
  description: This hook sets a standard for formatting TOML files.
  entry: pretty-format-toml
  language: python
  types: [toml]
    # for backward compatibility
  files: ^.*\.toml$
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-yaml
  name: Pretty format YAML
  description: This hook sets a standard for formatting YAML files.
  entry: pretty-format-yaml
  language: python
  types: [yaml]
    # for backward compatibility
  files: ^.*\.(yaml|yml)$
  minimum_pre_commit_version: 0.15.0
