repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-json
        exclude: ^test-data/.*$
    -   id: check-yaml
        exclude: ^test-data/.*$
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: name-tests-test
    -   id: pretty-format-json
        args: ['--autofix', '--indent', '4']
    -   id: requirements-txt-fixer
        files: ^requirements-dev\.txt$
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.10.3
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.1.0
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.4.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
