- id: pretty-format-golang
  name: Go Formatter
  description: Runs gofmt over golang source files.
  entry: pretty-format-golang
  language: python
  types: [go]
  files: ''
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-ini
  name: Pretty format INI
  description: This hook sets a standard for formatting INI  files.
  entry: pretty-format-ini
  language: python
  types: [ini]
    # for backward compatibility
  files: ''
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-java
  name: Google Java Formatter
  description: Runs Google Java Formatter over Java source files
  entry: pretty-format-java
  language: python
  types: [java]
  files: ''
  require_serial: true
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-kotlin
  name: KTLint
  description: Runs KTLint over Kotlin source files
  entry: pretty-format-kotlin
  language: python
  types: [kotlin]
  files: ''
  minimum_pre_commit_version: 0.15.0
  require_serial: true  # this is needed because the tool does use git commands internally to evanuate diffs
- id: pretty-format-rust
  name: cargo-fmt
  description: Runs cargo fmt over Rust source files
  entry: pretty-format-rust
  language: python
  types: [rust]
  files: ''
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-toml
  name: Pretty format TOML
  description: This hook sets a standard for formatting TOML files.
  entry: pretty-format-toml
  language: python
  types: [toml]
    # for backward compatibility
  files: ''
  minimum_pre_commit_version: 0.15.0
- id: pretty-format-yaml
  name: Pretty format YAML
  description: This hook sets a standard for formatting YAML files.
  entry: pretty-format-yaml
  language: python
  types: [yaml]
    # for backward compatibility
  files: ''
  minimum_pre_commit_version: 0.15.0
