language: python
matrix:
  include:
  - python: '2.7'
  - python: '3.6'
  - python: '3.6'
    env: TOXENV=pre-commit
  - python: '3.6'
    env: TOXENV=coverage
  - python: '3.7'
    sudo: required
    dist: xenial

before_install:
- curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly --verbose -y
- export PATH=${HOME}/.cargo/bin:${PATH}
- rustup component add rustfmt-preview --toolchain nightly

install: pip install codecov tox-travis
script:
  # create cache directory as pre-commit would do
- mkdir -p ${HOME}/.cache/pre-commit
- tox
after_success:
- if [ "$TOXENV" == "coverage" ]; then codecov; fi

sudo: false
