language: python
matrix:
  include:
  - python: '2.7'
  - python: '3.6'
  - python: '3.6'
    env: TOXENV=pre-commit
  - python: '3.6'
    env: TOXENV=coverage
  - python: '3.7'
    sudo: required

before_install:
# Initialize rust only if it is not already present (handle the case in which cache is empty)
- if [ ! -d ${HOME}/.cargo/bin/ ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly --verbose -y; fi
# Install rustfmt-preview component only if it is not alraedy installed (handle the case in which cache is empty)
- if ! ${HOME}/.cargo/bin/rustup component list | grep -Eq '^rustfmt-preview[^ ]* +\(installed\)$'; then ${HOME}/.cargo/bin/rustup component add rustfmt-preview --toolchain nightly; fi
- export PATH=${HOME}/.cargo/bin:${PATH}

install: pip install codecov tox-travis
script:
  # create cache directory as pre-commit would do
- mkdir -p ${HOME}/.cache/pre-commit
- tox
after_success:
- if [ "$TOXENV" == "coverage" ]; then codecov; fi

dist: xenial
sudo: false

cache:
  directories:
  - $HOME/.cache/pre-commit
  - $HOME/.cargo/
  - $HOME/.rustup/
