name: Build

on:
  push:
    branches:
    - master
    - maci-*
  pull_request:
    branches:
    - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pyversion: [3.6, 3.7, 3.8, 3.9]
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.pyversion }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '15'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4
    - name: Install Python dependencies
      run: pip install codecov tox tox-gh-actions
    - name: Run Tox
      run: tox
    - name: Upload coverage to Codecov
      if: ${{ success() }}
      uses: codecov/codecov-action@v1
      with:
        env_vars: OS,PYTHON

  precommit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: pip install tox
    - name: Run Tox
      run: tox -e pre-commit
