name: Build

on:
  push:
    branches:
    - master
    - maci-*
  pull_request:
    branches:
    - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pyversion: [2.7, 3.6, 3.7]
        os: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
        # Excluding tests on windows-python2.7 as there are failures on installing
        # ruamel.yaml and I'm not looking forward to add effort on improving the build
        # Windows tests will still be executed for python3+ so I guess that it should be fine
        - os: windows-latest
          pyversion: 2.7

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.pyversion }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2
    - name: Install Python dependencies
      run: pip install codecov tox tox-gh-actions
    - name: Run Tox
      run: tox
    - name: Upload coverage to Codecov
      if: ${{ success() }}
      uses: codecov/codecov-action@v1
      with:
        env_vars: OS,PYTHON

  precommit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: pip install tox
    - name: Run Tox
      run: tox -e pre-commit
